language: c
sudo: required
dist: trusty
compilers:
  - clang
  - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopus-dev
script:
  - cd 08 && make
notifications:
  webhooks: http://webhook.hakatashi.com/travis
